// All Finnish municipalities (kunnat) — every city/town Posti delivers to.
// Source: Statistics Finland municipality classification, 2026-01-01.
export const FINLAND_CITIES = [
  "Akaa", "Alajärvi", "Alavieska", "Alavus", "Asikkala", "Askola", "Aura",
  "Brändö", "Eckerö", "Enonkoski", "Enontekiö", "Espoo", "Eura", "Eurajoki",
  "Evijärvi", "Finström", "Forssa", "Föglö", "Geta", "Haapajärvi",
  "Haapavesi", "Hailuoto", "Halsua", "Hamina", "Hammarland", "Hankasalmi",
  "Hanko", "Harjavalta", "Hartola", "Hattula", "Hausjärvi", "Heinola",
  "Heinävesi", "Helsinki", "Hirvensalmi", "Hollola", "Huittinen",
  "Humppila", "Hyrynsalmi", "Hyvinkää", "Hämeenkyrö", "Hämeenlinna", "Ii",
  "Iisalmi", "Iitti", "Ikaalinen", "Ilmajoki", "Ilomantsi", "Imatra",
  "Inari", "Ingå", "Isojoki", "Isokyrö", "Jakobstad", "Janakkala",
  "Joensuu", "Jokioinen", "Jomala", "Joroinen", "Joutsa", "Juuka",
  "Juupajoki", "Juva", "Jyväskylä", "Jämijärvi", "Jämsä", "Järvenpää",
  "Kaarina", "Kaavi", "Kajaani", "Kalajoki", "Kangasala", "Kangasniemi",
  "Kankaanpää", "Kannonkoski", "Kannus", "Karijoki", "Karkkila",
  "Karstula", "Karvia", "Kaskinen", "Kauhajoki", "Kauhava", "Kauniainen",
  "Kaustinen", "Keitele", "Kemi", "Kemijärvi", "Keminmaa", "Kempele",
  "Kerava", "Keuruu", "Kihniö", "Kimitoön", "Kinnula", "Kirkkonummi",
  "Kitee", "Kittilä", "Kiuruvesi", "Kivijärvi", "Kokemäki", "Kokkola",
  "Kolari", "Konnevesi", "Kontiolahti", "Korsholm", "Korsnäs",
  "Koski Tl", "Kotka", "Kouvola", "Kristinestad", "Kronoby", "Kuhmo",
  "Kuhmoinen", "Kumlinge", "Kuopio", "Kuortane", "Kurikka", "Kustavi",
  "Kuusamo", "Kyyjärvi", "Kärkölä", "Kärsämäki", "Kökar", "Lahti",
  "Laihia", "Laitila", "Lapinjärvi", "Lapinlahti", "Lappajärvi",
  "Lappeenranta", "Lapua", "Larsmo", "Laukaa", "Lemi", "Lemland",
  "Lempäälä", "Leppävirta", "Lestijärvi", "Lieksa", "Lieto", "Liminka",
  "Liperi", "Lohja", "Loimaa", "Loppi", "Loviisa", "Luhanka", "Lumijoki",
  "Lumparland", "Luumäki", "Malax", "Mariehamn", "Marttila", "Masku",
  "Merijärvi", "Merikarvia", "Miehikkälä", "Mikkeli", "Muhos", "Multia",
  "Muonio", "Muurame", "Mynämäki", "Myrskylä", "Mäntsälä",
  "Mänttä-Vilppula", "Mäntyharju", "Naantali", "Nakkila", "Nivala",
  "Nokia", "Nousiainen", "Nurmes", "Nurmijärvi", "Nykarleby", "Närpes",
  "Orimattila", "Oripää", "Orivesi", "Oulainen", "Oulu", "Outokumpu",
  "Padasjoki", "Paimio", "Paltamo", "Pargas", "Parikkala", "Parkano",
  "Pedersöre", "Pelkosenniemi", "Pello", "Perho", "Petäjävesi",
  "Pieksämäki", "Pielavesi", "Pihtipudas", "Pirkkala", "Polvijärvi",
  "Pomarkku", "Pori", "Pornainen", "Porvoo", "Posio", "Pudasjärvi",
  "Pukkila", "Punkalaidun", "Puolanka", "Puumala", "Pyhtää", "Pyhäjoki",
  "Pyhäjärvi", "Pyhäntä", "Pyhäranta", "Pälkäne", "Pöytyä", "Raahe",
  "Raisio", "Rantasalmi", "Ranua", "Raseborg", "Rauma", "Rautalampi",
  "Rautavaara", "Rautjärvi", "Reisjärvi", "Riihimäki", "Ristijärvi",
  "Rovaniemi", "Ruokolahti", "Ruovesi", "Rusko", "Rääkkylä", "Saarijärvi",
  "Salla", "Salo", "Saltvik", "Sastamala", "Sauvo", "Savitaipale",
  "Savonlinna", "Savukoski", "Seinäjoki", "Sievi", "Siikainen",
  "Siikajoki", "Siikalatva", "Siilinjärvi", "Simo", "Sipoo", "Siuntio",
  "Sodankylä", "Soini", "Somero", "Sonkajärvi", "Sotkamo", "Sottunga",
  "Sulkava", "Sund", "Suomussalmi", "Suonenjoki", "Sysmä", "Säkylä",
  "Taipalsaari", "Taivalkoski", "Taivassalo", "Tammela", "Tampere",
  "Tervo", "Tervola", "Teuva", "Tohmajärvi", "Toholampi", "Toivakka",
  "Tornio", "Turku", "Tuusniemi", "Tuusula", "Tyrnävä", "Ulvila",
  "Urjala", "Utajärvi", "Utsjoki", "Uurainen", "Uusikaupunki", "Vaala",
  "Vaasa", "Valkeakoski", "Vantaa", "Varkaus", "Vehmaa", "Vesanto",
  "Vesilahti", "Veteli", "Vieremä", "Vihti", "Viitasaari", "Vimpeli",
  "Virolahti", "Virrat", "Vårdö", "Vörå", "Ylitornio", "Ylivieska",
  "Ylöjärvi", "Ypäjä", "Ähtäri", "Äänekoski",
] as const;
